main:
	BeginFunc 36 ;
	_tmp0 = 0 ;
	_tmp1 = 1 ;
	_tmp2 = _tmp0 < _tmp1 ;
	PushParam _tmp2 ;
	LCall _PrintBool ;
	PopParams 4 ;
	_tmp3 = 1 ;
	_tmp4 = 0 ;
	_tmp5 = _tmp3 < _tmp4 ;
	PushParam _tmp5 ;
	LCall _PrintBool ;
	PopParams 4 ;
	_tmp6 = 0 ;
	_tmp7 = 0 ;
	_tmp8 = _tmp6 < _tmp7 ;
	PushParam _tmp8 ;
	LCall _PrintBool ;
	PopParams 4 ;
	EndFunc ;
