main:
	BeginFunc 44 ;
	_tmp0 = LCall _ReadLine ;
	s = _tmp0 ;
	_tmp1 = "hello" ;
	_tmp2 = "goodbye" ;
	PushParam _tmp2 ;
	PushParam _tmp1 ;
	_tmp3 = LCall _StringEqual ;
	PopParams 8 ;
	PushParam _tmp3 ;
	LCall _PrintBool ;
	PopParams 4 ;
	_tmp4 = "hello" ;
	_tmp5 = "hello" ;
	PushParam _tmp5 ;
	PushParam _tmp4 ;
	_tmp6 = LCall _StringEqual ;
	PopParams 8 ;
	PushParam _tmp6 ;
	LCall _PrintBool ;
	PopParams 4 ;
	_tmp7 = "hello" ;
	PushParam s ;
	PushParam _tmp7 ;
	_tmp8 = LCall _StringEqual ;
	PopParams 8 ;
	PushParam _tmp8 ;
	LCall _PrintBool ;
	PopParams 4 ;
	EndFunc ;
